### ISSUE TITLE
Dependency Issue with h5py

### ISSUE THREAD

**Issue by project-delphi** [full-stack-deep-learning/conda-piptools#1]
Unresolved dependency issue, attempted with conda versions of both `py27` and `py35`

```
ERROR: Could not find a version that satisfies the requirement h5py==3.1.0 (from -r requirements/prod.in (line 4)) (from versions: 2.2.1, 2.3.0b1, 2.3.0, 2.3.1, 2.4.0b1, 2.4.0, 2.5.0, 2.6.0, 2.7.0rc2, 2.7.0, 2.7.1, 2.8.0rc1, 2.8.0, 2.9.0rc1, 2.9.0, 2.10.0)
Traceback (most recent call last):
  File "/opt/conda/envs/py35/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/piptools/scripts/compile.py", line 452, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/piptools/resolver.py", line 178, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/piptools/resolver.py", line 275, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/piptools/resolver.py", line 385, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/piptools/repositories/local.py", line 76, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/piptools/repositories/pypi.py", line 248, in get_dependencies
    download_dir, ireq, wheel_cache
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/piptools/repositories/pypi.py", line 203, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/pip/_internal/resolution/legacy/resolver.py", line 385, in _resolve_one
    dist = self._get_dist_for(req_to_install)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/pip/_internal/resolution/legacy/resolver.py", line 336, in _get_dist_for
    self._populate_link(req)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/pip/_internal/resolution/legacy/resolver.py", line 302, in _populate_link
    req.link = self._find_requirement_link(req)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/pip/_internal/resolution/legacy/resolver.py", line 267, in _find_requirement_link
    best_candidate = self.finder.find_requirement(req, upgrade)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/pip/_internal/index/package_finder.py", line 929, in find_requirement
    req)
pip._internal.exceptions.DistributionNotFound: No matching distribution found for h5py==3.1.0 (from -r requirements/prod.in (line 4))
make: *** [Makefile:13: pip-tools] Error 1
```

**Comment by sergeyk** [comment]
`environment.yml` specifies python 3.6
Cheers,
Sergey
